### ISSUE TITLE
Upgrade to python3

### ISSUE THREAD

**Issue by andersgs** [yatisht/strain_phylogenetics#6]
Hello. 

Nice package.

I noticed it is running on Python 2 though. Py2 has been sunsetted. Any plans to upgrade to Python3? Any particular reason it was written in Py2?

Thank you.

Anders.

**Comment by yatisht** [comment]
Hi Anders,

Thank you for your feedback. I have completed code migration to Python3. Please let me know if you still face some issues.

-Yatish

**Comment by andersgs** [comment]
Thank you @yatisht. Much appreciated. I'll close this for now. I'll re-open if I hit any issues.
